// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhmG9acIhymzVXhvGskGXGcHpa277pLG8',
    appId: '1:234323377186:web:8302f6ab9a66435e661e7b',
    messagingSenderId: '234323377186',
    projectId: 'ecommerce-5f9fb',
    authDomain: 'ecommerce-5f9fb.firebaseapp.com',
    storageBucket: 'ecommerce-5f9fb.appspot.com',
    measurementId: 'G-1BXWHRF5J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv_eRj9oObUdQlc-L3GfgZ7dEhRm8H8Js',
    appId: '1:234323377186:android:77567f72a5bd6a2d661e7b',
    messagingSenderId: '234323377186',
    projectId: 'ecommerce-5f9fb',
    storageBucket: 'ecommerce-5f9fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyFIEEh9BveRe9ar5AT-i9BhoM8IZJ9IU',
    appId: '1:234323377186:ios:015b98739749e963661e7b',
    messagingSenderId: '234323377186',
    projectId: 'ecommerce-5f9fb',
    storageBucket: 'ecommerce-5f9fb.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyFIEEh9BveRe9ar5AT-i9BhoM8IZJ9IU',
    appId: '1:234323377186:ios:ff1f7a8708ca601d661e7b',
    messagingSenderId: '234323377186',
    projectId: 'ecommerce-5f9fb',
    storageBucket: 'ecommerce-5f9fb.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
